apiVersion: v1
name: weather-monitoring-service
description: A Helm chart for Weather Monitoring Service
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - weather
  - monitoring
  - dropwizard
home: https://github.com/openrewrite-assist-testing-dataset/weather-monitoring-service
sources:
  - https://github.com/openrewrite-assist-testing-dataset/weather-monitoring-service
maintainers:
  - name: Weather Team
    email: weather-team@example.com