apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-monitoring-service.fullname" . }}-secret
  labels:
    {{- include "weather-monitoring-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc }}